# Generated by Django 6.0.4 on 2026-05-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_otp_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
