# Generated by Django 6.0.4 on 2026-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
