# Generated by Django 6.0.4 on 2026-05-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
