# Generated by Django 6.0.4 on 2026-05-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
