# Generated by Django 6.0.4 on 2026-05-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
