# Generated by Django 6.0.4 on 2026-05-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
