# Generated by Django 6.0.4 on 2026-05-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
