# Generated by Django 6.0.4 on 2026-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Seller', 'Seller')], default='Customer', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
