# Generated by Django 6.0.4 on 2026-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
