# Generated by Django 6.0.4 on 2026-05-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0039_remove_cartitem_created_at_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
