# Generated by Django 6.0.4 on 2026-05-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0042_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
    ]
