# Generated by Django 6.0.4 on 2026-05-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0044_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
    ]
