# Generated by Django 6.0.4 on 2026-05-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0047_review_delete_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
