# Generated by Django 6.0.4 on 2026-05-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0048_order_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
    ]
