# Generated by Django 6.0.4 on 2026-06-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0051_alter_cartitem_color_alter_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.color'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.size'),
        ),
    ]
