# Generated by Django 6.0.4 on 2026-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0052_productimage_color_productimage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
