# Generated by Django 6.0.4 on 2026-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0053_category_slug_product_slug_producttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
