# Generated by Django 6.0.4 on 2026-06-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0054_wishlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
