# Generated by Django 6.0.4 on 2026-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0056_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
