# Generated by Django 6.0.4 on 2026-06-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0058_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Seller', 'Seller')], default='normal', max_length=20),
        ),
    ]
