# Generated by Django 6.0.4 on 2026-06-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0063_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_coupons', to='User.order'),
        ),
    ]
